In [5]:
import numpy as np
import pandas as pd
import joblib

In [8]:

model = joblib.load("spam_model.pkl")
vectorizer = joblib.load("vectorization.pkl")
df = pd.read_csv("spam.csv",encoding="latin1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [12]:
df = df.rename(columns={'v1':"label",'v2':'Message'})
df = df[["label","Message"]]
df.head()

  label                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [13]:
X_test = vectorizer.transform(df['Message'])
Y_test = df['label']

In [14]:
Y_pred = model.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(f"Accuracy: {accuracy_score(Y_test,Y_pred)}")
print("Classification Report: ")
print(classification_report(Y_test,Y_pred))
print()
print("Confusion Matrix: ")
print(confusion_matrix(Y_test,Y_pred))

Accuracy: 0.9879755922469491
Classification Report:
              precision    recall  f1-score   support

         ham       1.00      0.99      0.99      4825
        spam       0.94      0.97      0.96       747

    accuracy                           0.99      5572
   macro avg       0.97      0.98      0.97      5572
weighted avg       0.99      0.99      0.99      5572


Confusion Matrix:
[[4781   44]
 [  23  724]]