In [3]:
import numpy as np
import pandas as pd
import pickle

In [4]:
vec = pickle.load(open('vectorizer.pkl','rb'))
model = pickle.load(open('model.pkl','rb'))

df = pd.read_csv("spam.csv",encoding="latin1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [5]:
df = df.rename(columns={'v1':"label",'v2':'Message'})
df = df[["label","Message"]]
df.head()

  label                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
X_test = vec.transform(df['Message'])
Y_test = df['label']

In [8]:
Y_pred = model.predict(X_test)

In [11]:

Y_test_numeric = Y_test.map({'ham': 0, 'spam': 1})

In [13]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,precision_score

print(f"Accuracy: {accuracy_score(Y_test_numeric, Y_pred)}")
print("Classification Report: ")
print(classification_report(Y_test_numeric,Y_pred))
print()
print("Confusion Matrix: ")
print(confusion_matrix(Y_test_numeric, Y_pred))
print(f"precision score: {precision_score(Y_test_numeric, Y_pred)}")

Accuracy: 0.9628499641062455
Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98      4825
           1       1.00      0.72      0.84       747

    accuracy                           0.96      5572
   macro avg       0.98      0.86      0.91      5572
weighted avg       0.96      0.96      0.96      5572


Confusion Matrix:
[[4824    1]
 [ 206  541]]
precision score: 0.9981549815498155